"""
Autogenerated stub. DO NOT MODIFY!
https://github.com/lemariva/micropython-camera-driver/raw/master/firmware/micropython_v1.21.0_camera_no_ble.bin
"""
from _typeshed import Incomplete as Incomplete

FRAME_VGA: int
FRAME_UXGA: int
GRAYSCALE: int
FRAME_WQXGA: int
FRAME_XGA: int
FRAME_QVGA: int
FRAME_QSXGA: int
FRAME_SXGA: int
FRAME_QXGA: int
FRAME_SVGA: int
YUV422: int
WB_SUNNY: int
WB_OFFICE: int
JPEG: int
XCLK_10MHz: int
XCLK_20MHz: int
RGB565: int
PSRAM: int
WB_NONE: int
WB_CLOUDY: int
WB_HOME: int
EFFECT_RED: int
EFFECT_NONE: int
FRAME_96X96: int
EFFECT_RETRO: int
FRAME_240X240: int
EFFECT_BLUE: int
DRAM: int
EFFECT_NEG: int
EFFECT_BW: int
EFFECT_GREEN: int
FRAME_QQVGA: int
FRAME_P_HD: int
FRAME_P_FHD: int
FRAME_CIF: int
FRAME_QCIF: int
FRAME_QHD: int
FRAME_HD: int
FRAME_FHD: int
FRAME_P_3MP: int
FRAME_HQVGA: int
FRAME_HVGA: int


def mirror(*args, **kwargs) -> Incomplete: ...


def whitebalance(*args, **kwargs) -> Incomplete: ...


def init(*args, **kwargs) -> Incomplete: ...


def speffect(*args, **kwargs) -> Incomplete: ...


def quality(*args, **kwargs) -> Incomplete: ...


def saturation(*args, **kwargs) -> Incomplete: ...


def capture(*args, **kwargs) -> Incomplete: ...


def framesize(*args, **kwargs) -> Incomplete: ...


def brightness(*args, **kwargs) -> Incomplete: ...


def flip(*args, **kwargs) -> Incomplete: ...


def contrast(*args, **kwargs) -> Incomplete: ...


def deinit(*args, **kwargs) -> Incomplete: ...
